export const endpoint = 'https://app.falconcranes.co.uk';

export const colours = {
  buttonTitle: 'black',
  noResultsPanelBackground: '#F1F1EC',
};

export const font = {
  fontFamily: 'FiraSansCondensed-Light',
};

export const input = {
  textInput: {
    height: 60,
    width: '100%',
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 20,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
  },
  textInputLong: {
    height: 130,
    width: '100%',
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 10,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
  },
  textInputNarrow: {
    height: 40,
    width: 50,
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    borderRadius: 10,
    paddingLeft: 20,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
    justifyContent: 'center',
  },
  textInputMedium: {
    height: 40,
    width: 80,
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    borderRadius: 10,
    paddingLeft: 20,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
    justifyContent: 'center',
  },
  textInputShort: {
    height: 60,
    width: '50%',
    margin: 3,
    backgroundColor: 'white',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    borderRadius: 10,
    paddingLeft: 20,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
    textAlign: 'left',
  },
  textInputModel: {
    height: '80%',
    width: '100%',
    margin: 3,
    backgroundColor: 'white',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    borderRadius: 10,
    paddingLeft: 20,
    fontWeight: '400',
    fontFamily: font.fontFamily,
    textAlign: 'left',
    paddingTop: 0,
    paddingBottom: 0,
    color: 'black',
    flex: 1,
    textAlignVertical: 'top',
    lineHeight: 23,
  },
  dropDown: {
    height: 60,
    width: '80%',
    margin: 3,
    backgroundColor: 'white',
    borderColor: '#C8C8C8',
    borderWidth: 3,
    paddingLeft: 10,
    fontWeight: '600',
    fontFamily: font.fontFamily,
    textAlign: 'left',
    color: 'black',
  },
  search: {
    height: 40,
    borderWidth: 1,
    paddingLeft: 20,
    margin: 5,
    borderColor: '#fdc73e',
    backgroundColor: '#FFFFFF',
    fontColor: 'black',
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
  },
  placeHolderColor: '#BDBDBD',
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 32,
    marginTop: 15,
    elevation: 3,
    width: 200,
    backgroundColor: '#fdc73e',
    fontFamily: font.fontFamily,
    marginBottom: 5,
    color: 'black',
  },

  buttonDisabled: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 32,
    marginTop: 15,
    elevation: 3,
    width: 200,
    backgroundColor: 'grey',
    fontFamily: font.fontFamily,
    marginBottom: 5,
    color: 'black',
  },

  loginInput: {
    height: 40,
    width: '100%',
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 20,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
  },

  passwordChangeInput: {
    height: 40,
    width: '70%',
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 20,
    fontWeight: '400',
    color: 'black',
    fontFamily: font.fontFamily,
  },

  orderFormDropDown: {
    height: 60,
    width: '100%',
    margin: 3,
    backgroundColor: 'white',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 10,
    fontWeight: '400',
    fontFamily: font.fontFamily,
    textAlign: 'left',
    color: 'black',
  },
  textInputWorkCarriedOut: {
    height: 60,
    width: '100%',
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 5,
    fontWeight: '400',
    fontFamily: font.fontFamily,
    color: 'black',
  },
  textInputWorkComment: {
    height: 100,
    width: '100%',
    margin: 3,
    backgroundColor: '#fff',
    borderColor: '#C8C8C8',
    borderWidth: 0.5,
    paddingLeft: 5,
    fontWeight: '400',
    fontFamily: font.fontFamily,
    color: 'black',
  },
};
